#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
from rhvoice_preprocessing.rhvoice_say import rhvoice_say


if len(sys.argv) > 1:
    text = sys.argv[1]
    rhvoice_say(text)
else:
    print('Нет текста для чтения...')
